.Dd $Mdocdate: November 26 2021$
.Dt FM 1
.Os
.Sh NAME
.Nm fm
.Nd file manager
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl hv
.Op Fl d Ar file
.Op Fl m Ar file
.Op Ar directories...
.Ek
.Sh DESCRIPTION
.Nm
is an utility designed to browse the filesystem via a tabbed interface.
.Pp
The arguments are as follows:
.Bl -tag -width 14m
.It Fl d Ar file
Write the last visited path to
.Ar file
before exiting.
.It Fl h , Fl -help
Print help message and exit.
.It Fl m Ar file
Write the path of all the marked entries to
.Ar file
upon exiting.
.It Fl v , Fl -version
Print program version and exit.
.El
.Pp
In its most basic usage,
.Nm
will gather a list of directory entries and present it on the screen.
There is always one
.Pq and only one
highlighted entry visible.
This is both the cursor location and the current selection.
.Pp
It's also possible to select all the entries to be processed and apply
the same command to all of them: this is called the mark.
Unlike simple selection, the effect of marks is not constrained by
visibility: marks are shared across all the tabs.
For such purpose,
.Nm
allows an arbitrary number fo entries to be marked, with the only
limitation that they must be all in the same directory.
.Pp
There are ten tabs in total, numbered from 0 to 9, but only one tab is
visible on the screen at any given moment.
The number associated with the current tab is visible on the right corner
of the screen.
It's possible to set the current working directory for the tabs at start
up by passing the desired paths as extra command-line arguments.
The tab at index 0 always starts at
.Ev $HOME .
If more than nine directories are specified, the extra ones will be
silently discarded.
Tabs for wich an invalid path was assigned will also start at
.Ev $HOME .
By default tabs starts at the current working directory.
.Sh KEYS
These commands are currently recognized
.Pq ^L refers to control-L and M-a to meta-a
.Pp
.Bl -tag -width 20m -compact
.It ?
Display
.Nm
manual page.
.It ^ | h | b
Go up to previous directory.
.It H
Go to home directory.
.It J | ^V | page down
Scroll down by one screen.
.It K | M-v | page up
Scroll up by one screen.
.It ^G
Do nothing.
.It j | n | ^N | down
Scroll down by one line.
.It k | p | ^P | up
Scroll up by one line.
.It l | f
Go to selected directory.
.It Y
Copy current path.
.It P
Paste path
.Pq goto previously copied path.
.It ^L
Refresh and redraw screen.
.It ^M
Spawn a shell
.It q
Quit
.Nm .
.El
.Sh SEE ALSO
.Xr mc 1 ,
.Xr nnn 1 ,
.Xr noice 1 ,
.Xr ranger 1 ,
.Xr rover 1 ,
.Xr vifm 1
.Sh HISTORY
.Nm
was forked from
.Xr rover 1 .
.Sh CAVEATS
.Nm
never asks for confirmation before overwriting existing files.
Please be careful.
